name: archetype
services:
  postgresold:
    image: postgres:10 # You can change the version to match your old database version
    container_name: postgres_db_old
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgresold
    volumes:
      - ./old.sql:/docker-entrypoint-initdb.d/init.sql # provide a old.sql file in the same directory as this docker-compose.yaml file to initialize the database with your old data
      #- postgres_data:/var/lib/postgresql/data # By default no volume is created, so the database will be lost when the container is removed. Uncomment this line to persist the data.
    restart: unless-stopped



