# Generated by Django 6.0.7 on 2026-07-30 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_carouselitem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('logo', models.ImageField(help_text='The logo for this partner', upload_to='partners')),
                ('name', models.CharField(help_text="The partner's name", max_length=150)),
                ('url', models.CharField(blank=True, help_text='Full URL or relative path (e.g. /about).', max_length=200, validators=[django.core.validators.RegexValidator('^(https?://.+|/.*)$', 'Enter a full URL or a relative path starting with /.')])),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
